### PR TITLE
Fix session finish problem

### LINKED ISSUE #578: AdMob banners don't send OM event sessionFinish
**Expected behavior**
AdMob banner after leaving page must send OM sessionFinish request. But it sends only geometryChange. All other primary ad servers works fine.

### LINKED ISSUE #613: MRAID Resize problem
**Bug**
After clicking 'Click to Resize' on MRAID: Resize and then clicking on arrow button on top bar, MRAID Resize screen is displayed throughout all application flow

**To Reproduce**
1. Go to MRAID Resize (In-App) (or GAM doesn't matter)
2. Click on 'Click to Resize'
3. Click arrow button on top bar
4. See MRAID Resize screen in the main menu

**Expected behavior**
Initial ui screen before navigating to MRAId

**Screenshots**
Снимок экрана 2023-04-20 в 16 38 19

### LINKED ISSUE #614: Session finish event is not sent after applying rendering delegation feature
**Describe the bug**
OM SDK `sessionFinish` event is not sent. `PrebidDisplayView` has the method `destroy()` but it is not called.

### PR DESCRIPTION
**Pull request by ValentinPostindustria**
Closes #614.  Closes #613. Closes #578.

### CODE REVIEW

**Review by MaksPetrukhnoPI — APPROVED** [review]

File: PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/PrebidDisplayView.java [hunk 1]
```diff
@@ -127,7 +136,7 @@ public void onClickThroughClosed(
     };
     public PrebidDisplayView(
             @NonNull Context context,
-            DisplayViewListener listener,
+            @Nullable DisplayViewListener listener,
```
Comment (YuriyVelichkoPI) [inline PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/api/rendering/PrebidDisplayView.java:139]: the `@Nullable` doesn't correspond interface declaration. Does it make sense to change the interface?

**Review by MaksPetrukhnoPI — APPROVED** [review]
