### PR TITLE
NetworkOnMainThreadException Fix

### LINKED ISSUE #678: NetworkOnMainThreadException when destroying MediationBannerAdUnit
**Describe the bug**
We recently upgraded the Prebid SDK from version 2.1.0 to 2.1.3. After this update, we encountered a new runtime crash scenario when attempting to destroy the `MediationBannerAdUnit`. It appears that this operation is now attempting to perform network operations synchronously, resulting in the Android system throwing a `NetworkOnMainThreadException`.

If `MediationBannerAdUnit.destroy` is not intended to be called from the main thread, I suggest adding an explicit check and update documentation to make it easier for developers to identify and prevent such calls.

**To Reproduce**
This issue is not easily reproducible and requires specific conditions to trigger. Our discovery of this problem was based on analysis of production logs.

**Stacktrace**
```
Caused by android.os.NetworkOnMainThreadException:
       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
       at com.google.android.gms.org.conscrypt.Platform.blockGuardOnNetwork(:com.google.android.gms@233217015@23.32.17 (040300-560149384):5)
       at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.shutdownAndFreeSslNative(:com.google.android.gms@233217015@23.32.17 (040300-560149384):1)
       at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.close(:com.google.android.gms@233217015@23.32.17 (040300-560149384):79)
       at com.android.okhttp.Connection.closeIfOwnedBy(Connection.java:1303)
       at com.android.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:78)
       at com.android.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:137)
       at com.android.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:319)
       at com.android.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:739)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:126)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
       at com.google.firebase.perf.network.InstrURLConnectionBase.disconnect(InstrURLConnectionBase.java:81)
       at com.google.firebase.perf.network.InstrHttpsURLConnection.disconnect(InstrHttpsURLConnection.java:63)
       at org.prebid.mobile.rendering.networking.BaseNetworkTask.destroy(BaseNetworkTask.java:141)
       at org.prebid.mobile.rendering.networking.modelcontrollers.Requester.destroy(Requester.java:86)
       at org.prebid.mobile.rendering.bidding.loader.BidLoader.destroy(BidLoader.java:180)
       at org.prebid.mobile.api.mediation.MediationBaseAdUnit.destroy(MediationBaseAdUnit.java:275)
       at org.prebid.mobile.api.mediation.MediationBannerAdUnit.destroy(MediationBannerAdUnit.java:60)

### PR DESCRIPTION
**Pull request by jsligh**
Closes #678

### CODE REVIEW

File: PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java [hunk 1]
```diff
@@ -82,10 +83,32 @@ public abstract class Requester {
...
+     * on a background thread or it throws a NetworkOnMainThreadException
+     **/
+    private static class DestroyNetworkTaskAsyncTask extends  AsyncTask<BaseNetworkTask, Void, Void> {
+
+        @Override
+        protected Void doInBackground(BaseNetworkTask... baseNetworkTasks) {
+            if (baseNetworkTasks.length > 0) {
+                if (baseNetworkTasks[0] != null) {
+                    baseNetworkTasks[0].cancel(true);
+                    baseNetworkTasks[0].destroy();
```
[the remark this answers is not in the document]
Comment (YuriyVelichkoPI) [reply PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java:97]: And we need to be sure that `BaseNetworkTask` manages the _cancel_ event properly. For all use cases.

File: PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java [hunk 2]
```diff
@@ -82,10 +83,31 @@ public abstract class Requester {
 
     public abstract void startAdRequest();
 
+    /**
+     * This Async task is needed because the networkTask needs to be cancelled / destroyed
+     * on a background thread or it throws a NetworkOnMainThreadException
+     **/
+    private static class DestroyNetworkTaskAsyncTask extends  AsyncTask<BaseNetworkTask, Void, Void> {
```
Comment (YuriyVelichkoPI) [inline PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java:90]: I meant that `DestroyNetworkTaskAsyncTask` doesn't have much sense since it just helps to make a call to the thread not from the main thread, but still, it is not correct interprocess communication that may lead to unexpected behavior. 

The `networkTask.cancel(true)` should did all the job.

Comment (YuriyVelichkoPI) [reply PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/networking/modelcontrollers/Requester.java:90]: Can we try to remove the DestroyNetworkTaskAsyncTask at all? As for me, it just adds one more multithread call but doesn't influence the general behavior. networks.cancel(true) should stop the thread gracefully without direct communication with the network layer so the error should not appear. 

The error in the initial ticket appears due to the networkTask.destroy(); call wich triggers the network communication on the main thread.

**Review by YuriyVelichkoPI — CHANGES_REQUESTED** [review]
Please review the comment. If we can solve the issue with less code it would be great. If it appears that we still need the extra class - we will keep it. But we at least will try.
