### PR TITLE
Unification corrections

### LINKED ISSUE #370: Unify the bid requesting for original and rendering API
## Motivation

SDK shouldn't have duplications in the functionality and codebase.

## Description

The rendering functionality was added as part of the Prebid Mobile SDK. It was released under the `beta` label and didn't affect the original codebase at all. So publishers were able to update SDK safely for the current integration and try the rendering API.

V1 13

As the result, SDK got several architectural issues:
- duplicated codebase for 
    - targeting
    - GDPR/CCPA
    - RTB builder
    - bid requesting
- similar but still different API for MoPub Integration. 

The duplication leads to well-known support problems and reliability issues. We have to mitigate them by taking the best parts of the two worlds. As a result, publishers will receive solid, convenient, and reliable Prebid SDK. 

## Objectives

V1 14

- Unify the targeting configuration objects
- Unify the RTB Builder
- Unify the  bid requestor
- Update Unit tests
- Update Integration examples
- Update autotests
- Update demo apps 

## Unification Steps

The bid requesting parts are pretty similar in Original and Rendering API.

Unification steps

It consists of the next functional blocks:
- Ad Units classes (basically the **API**)
- Configuration classes (**Targeting API**)
- RTB Builder - the class responsible for assembling the proper RTB request (version 2.5)
- Bid Requester - the class responsible for managing network requests
- Bid Response - the class that provides the RTB model of the bid response. 

From the functional perspective, the `RTB Builder` and `Bid Requester` are almost identical in both codebases. They just do their job - assembly RTB requests and make the HTTP bid Request. So there are no regression risks here. 

However, the `Targeting API`, `Ad Unit Configuration Classes`, and the `Bid Response` are different.  So we should organize the migration process in such a way that will bring us great confidence in the absence of regression in the result. 

In order to address the regression risks, we will replace components in the steps below. These steps will allow us to be sure (on the binary level) that no functionality of the original API is lost.  

### Step 1: Interfaces

Objective: Introduce interfaces (protocols) for the original classes, which declares component's features:

Unification steps - interfaces

### Step 2: Modify Rendering API

Objectives: 
- Confirm the Rendering API to protocols of Original classes.
- Utilize the protocols of original APIs in Rendering RTB Builder
- Confirm the Rendering Bid Request to the protocol of the Original API

### Step 3: Replace the Original Classes 

Unification steps - Replacement

Objectives:

- Replace It consists of the next functional blocks
  - Targeting API
  - RTB builder
  - Bid Requester
  - Bid Response
- Update unit tests

## Implementation roadmap

In order to complete unification need to solve the next tasks:

**Introduce temporary interfaces**:
- [x] Ad Unit Configuration
- [x] SDK Targeting
- [x] SDK Configuration
- [x] Bid Response

**Confirm classes from the rendering codebase to the transitional protocols**:
- [x] Confirm interface to AdUnitConfiguration
- [x] Confirm interface to PrebidRenderingTargeting
- [x] Confirm interface to PrebidRenderingConfig
- [x] Confirm interface to BidResponseForRendering

**Replace classes**
- [x] Use AdUnitConfiguration
- [x] Use PrebidRenderingTargeting
- [x] Use PrebidRenderingConfig
- [x] Use BidResponseForRendering

**Cleaning**
- [x] Fix tests
- [x] Remove old files

### PR DESCRIPTION
**Pull request by ValentinPostindustria**
Remove unused files. Remove tests for removed classes from the original API. Fix NativeImageAsset problems. Closes #370.

### CODE REVIEW

File: PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java [hunk 1]
```diff
@@ -62,7 +62,7 @@
      * Default refresh interval. 60 seconds
      * Used when the refresh interval is not in the AUTO_REFRESH_DELAY_MIN & AUTO_REFRESH_DELAY_MAX range.
      */
-    public static final int AUTO_REFRESH_DELAY_DEFAULT = 60_000;
+    public static final int AUTO_REFRESH_DELAY_DEFAULT = 0;
```
Comment (YuriyVelichkoPI) [inline PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/PrebidMobile.java:65]: This change is looked inconvenient. Why did we change this value? If the change is really needed, we should update its description as well.

File: PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/JsonUserDataTest.java [hunk 2]
```diff
@@ -27,7 +27,7 @@ public void putUsersDataListToRequestParams_addElementsToOutsideList_elementsAdd
 
         AdUnitConfiguration configuration = new AdUnitConfiguration();
         configuration.setConfigId("configId");
-        configuration.setAdType(AdType.BANNER);
+        configuration.setAdUnitIdentifierType(AdUnitConfiguration.AdUnitIdentifierType.BANNER);
```
Comment (YuriyVelichkoPI) [inline PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/JsonUserDataTest.java:30]: This change looks not super accurate. 

```
configuration.setAdType(AdType.BANNER);
```

Looks better than 

```
configuration.setAdUnitIdentifierType(AdUnitConfiguration.AdUnitIdentifierType.BANNER);
```

My suggestions here are:

- Rename the `AdUnitIdentifierType` to `AdFormat`.
- Make the `AdFormat` a global type like the `AdType` was before.
- Rename the setter and getter from `AdUnitIdentifierType` to `AdFormat`

**Review by YuriyVelichkoPI — CHANGES_REQUESTED** [review]

File: PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/JsonUserDataTest.java (hunk 2 above)
Comment (YuriyVelichkoPI) [reply PrebidMobile/PrebidMobile-core/src/test/java/org/prebid/mobile/JsonUserDataTest.java:30]: Please, do not apply these changes to the current PR. We'll do it later in the scope of introducing the rendering controls. There will be a lot of work related to the AdUnitConfiguration

**Review by YuriyVelichkoPI — APPROVED** [review]
LGTM
