### PR TITLE
Run getGlobalVisibleRect on the main thread instead of a background thread

### LINKED ISSUE #735: Crash for MRAID ads
**Describe the bug**
The bug was reported in the Slack channel: 

I just noticed that the JavaScriptInterface method getCurrentPosition inhence the UI related method View.getGlobalVisibleRect is called in JavaBridge thread, which is a background thread. And this causes a lot of native crashes in our app.

https://github.com/prebid/prebid-mobile-android/blob/master/PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/webview/mraid/BaseJSInterface.java#L175

**To Reproduce**

No steps. Prod crash.

**Expected behavior**

No crash. 

**Screenshots**

image

image

**Smartphone (please complete the following information):** 

- Android

### PR DESCRIPTION
**Pull request by jsligh**
Closes #735

### CODE REVIEW

File: PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/webview/mraid/BaseJSInterface.java [hunk 1]
```diff
@@ -171,9 +171,8 @@ public String getDefaultPosition() {
     public String getCurrentPosition() {
         JSONObject position = new JSONObject();
         Rect rect = new Rect();
-
-        adBaseView.getGlobalVisibleRect(rect);
-
+        Handler mainHandler = new Handler(Looper.getMainLooper());
+        mainHandler.post(() -> adBaseView.getGlobalVisibleRect(rect));
```
Comment (YuriyVelichkoPI) [inline PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/webview/mraid/BaseJSInterface.java:175]: The quick search shows that there are more than 20 usages of the `adBaseView` object in the `BaseJSInterface` class. 

image

I'm afraid any of them can lead to a similar crash.

I'd suggest really, hard to reproduce the current crash first, then fix it, then try to reproduce with other usages of the `adBaseView` before the release. It will help to understand the curcomstanses and prevent other crashes, potentially in the same ads. 

If we can't reproduce it, of course, we need to release the fix based on the assumptions, but it is better to cover as much potential cases as possible. Otherwice we will get the same crash statistic but with another method, for example: ` adBaseView.getGlobalVisibleRect(rect)`

**Review by YuriyVelichkoPI — CHANGES_REQUESTED** [review]

File: PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/webview/mraid/BaseJSInterface.java (hunk 1 above)
Comment (YuriyVelichkoPI) [reply PrebidMobile/PrebidMobile-core/src/main/java/org/prebid/mobile/rendering/views/webview/mraid/BaseJSInterface.java:177]: It looks like the Handler runs the task asynchronously. However, we need the data synchronously to process it in the next step.

image

**Review by YuriyVelichkoPI — APPROVED** [review]
Ok, it should fix the current crash. But I'm not sure about all other possible cases. 

Ideally, since we've faced such an issue, we should wrap a managed WebView in some background-thread-safe-invocation wrapper. To make sure that all clients of the JS bridge (ad code and SDK code) can use in safely. It could be done in the scope of the separate tech debt ticket.

**Comment by YuriyVelichkoPI** [comment]
I think we should release this hotfix as soon as possible, since it leads to multiple crashes right now.
